[pdk]
name = "example_pdk"

[layers.met1]
family = true
primary = "met1_drawing"
pin = "met1_pin"

[layers.met1_drawing]
gds = (1, 2)

[layers.met1_pin]
gds = (1, 3)

[layers.via1]
gds = (3, 4)

[layers.met2]
gds = (5, 6)


[vias.via1]
[[vias.via1.geometry]]
rect = (-100, -100, 100, 100)
layer = "met1"

[[vias.via1.geometry]]
rect = (-50, -50, 50, 50)
layer = "via1"

[[vias.via1.geometry]]
rect = (-100, -100, 100, 100)
layer = "met2"

[mos]

[mos.nmos_svt]
# sizes are (w, l, nf)
sizes = [(600, 150, 1), (605, 150, 1), (610, 150, 1)]
supply = "1.8"
kind = "nmos"

[mos.nhv]
# sizes are (w, l, nf)
sizes = [(600, 150, 1), (605, 150, 1), (610, 150, 1)]
supply = "3.3"
kind = "nmos"

[stdcell]

[stdcell.sky130_fd_sc_hd__and2_1]
function = "and2"
scale = 1
gds = "/path/to/sky130_fd_sc_hd__and2_1.gds"
spice = "/path/to/sky130_fd_sc_hd__and2_1.spice"
lib = "/path/to/sky130_fd_sc_hd__and2_1.lib"

[corners]

# naming convention for this made up PDK is NMOS/PMOS/Resistor
[corners.ttt]
sim_includes = ["/path/to/nmos_typ.spice", "/path/to/pmos_typ.spice", "/path/to/res_typ.spice"]

[corners.sfs]
sim_includes = ["/path/to/nmos_slow.spice", "/path/to/pmos_fast.spice", "/path/to/res_slow.spice"]
