[package]
name = "substrate"
version = "0.0.0"
edition = "2021"

[dependencies]
arcstr = "1.1.5"
serde = { version = "1.0.164", features = ["derive"] }
slotmap = "1.0.6"
state = "0.6.0"
once_cell = "1.18.0"

[features]
test = []
